name: 'Handle new issue comment'
on:
  issue_comment:
    types: [created]

jobs:
  handle_new_issue_comment:
    runs-on: ubuntu-latest
    name: Handle new issue comment
    steps:
      - name: Toggle awaiting-reply label
        uses: jd-0001/gh-action-toggle-awaiting-reply-label@v2.0.0
        with:
          label: awaiting-reply